config/routes.rb
Educaucinicial::Application.routes.draw do

  get "escalas/new"

  get "escalas/create"

  get "escalas/index"

  get "escalas/show"

  get "escalas/edit"

  get "escalas/update"

  get "escalas/destroy"

  resources :usuarios, :jardins, :escalas, :salas

  resources :evaluacions do
    resources :salas
  end

  get "logout" => "sesion#logout", :as => "logout"
  get "login" => "sesion#login", :as => "login"
  get "profile" => "sesion#profile", :as => "profile"
  get "password" => "sesion#password", :as => "password"
  get "evaluacions/:id/informe" => "evaluacions#informe", :as => :informe
  get "evaluacions/:id/to_excel" => "evaluacions#to_excel", :as => :to_excel

  match ':controller(/:action(/:id))(.:format)'

  root :to => 'evaluacions#index'

end

app/models/jardin.rb
class Jardin < ActiveRecord::Base
  attr_accessible :nombre, :contacto, :direccion, :email, :telefono
  has_many :evaluacions

  validates :nombre, :presence => true
  validates :contacto, :presence => true
  validates :direccion, :presence => true
  validates :email, :email => true
end

app/controllers/jardins_controller.rb
#<Encoding:UTF-8>
class JardinsController < ApplicationController

  before_filter :authenticate_user

  def index
    @jardins = Jardin.all
  end

  def show
    @jardin = Jardin.find(params[:id])
  end

  def new
    @jardin = Jardin.new
  end

  def edit
    @jardin = Jardin.find(params[:id])
  end

  def create
    @jardin = Jardin.new(params[:jardin])

    if @jardin.save
      redirect_to @jardin, notice: 'El jardín fue registrado.'
    else
      render action: "new"
    end
  end

  def update
    @jardin = Jardin.find(params[:id])
    if @jardin.update_attributes(params[:jardin])
      redirect_to @jardin, notice: 'El jardín fue actualizado.'
    else
      render action: "edit"
    end
  end

  def destroy
    Jardin.find(params[:id]).destroy
    redirect_to jardins_url
  end
end

app/helpers/jardins_helper.rb
module JardinsHelper
end

app/views/jardins/_form.html.erb
<%= form_for(@jardin) do |f| %>
  <% if @jardin.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @jardin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>Nombre del jardín<br> <%= f.text_field :nombre %></p>

  <p>Dirección<br> <%= f.text_field :direccion %></p>

  <p>Persona de contacto<br> <%= f.text_field :contacto %></p>

  <p>Teléfono<br> <%= f.phone_field :telefono %></p>

  <p>Email<br> <%= f.email_field :email %></p>

  <button type="submit" class="btn btn-success">
    <i class="icon-check"></i>  Guardar
  </button>
<% end %>

app/views/jardins/edit.html.erb
<h1>Editando el jardín</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @jardin %> |
<%= link_to 'Volver', jardins_path %>

app/views/jardins/index.html.erb
<h1>Jardines registrados</h1>

<%= link_to 'Nuevo jardín', new_jardin_path, :class => 'btn btn-success up-right' %>

<% if !@jardins.blank? %>
<table class="table table-striped">
  <thead>
    <th>Nombre del jardín</th>
    <th>Dirección</th>
    <th>Persona de contacto</th>
    <th>Teléfono</th>
    <th>Email</th>
    <th></th>
    <th></th>
  </thead>

<% @jardins.each do |jardin| %>
  <tr>
    <td><%= jardin.nombre %></td>
    <td><%= jardin.direccion %></td>
    <td><%= jardin.contacto %></td>
    <td><%= jardin.telefono %></td>
    <td><%= jardin.email %></td>
    <td>
      <%= link_to edit_jardin_path(jardin) do %>
        <i class="icon-pencil"></i>
      <% end %>
    </td>
    <td>
      <%= link_to jardin, method: :delete, data: { confirm: '¿Estás seguro?' } do %>
        <i class="icon-trash"></i>
      <% end %>
    </td>
  </tr>
<% end %>
</table>
<% else %>
<p>Aún no se han ingresado jardines. 
  Haz clic en el botón <strong>nueva jardín</strong> para registrar un jardín.</p>
<% end -%>

app/views/jardins/new.html.erb
<h1>Nuevo jardín</h1>

<%= render 'form' %>
<%= link_to 'Volver', jardins_path %>

app/views/jardins/show.html.erb
<h1>Jardín</h1>
<h2><%= @jardin.nombre %></h2>

<p>Contacto:<br> <%= @jardin.contacto %></p>

<p>Dirección:<br> <%= @jardin.direccion %></p>

<p>Email:<br> <%= @jardin.email %></p>

<p>Teléfono:<br> <%= @jardin.telefono %></p>

<%= link_to 'Editar', edit_jardin_path(@jardin) %>
<%= link_to 'Volver', jardins_path %>