config/routes.rb
Educaucinicial::Application.routes.draw do

  get "escalas/new"

  get "escalas/create"

  get "escalas/index"

  get "escalas/show"

  get "escalas/edit"

  get "escalas/update"

  get "escalas/destroy"

  resources :usuarios, :jardins, :escalas, :salas

  resources :evaluacions do
    resources :salas
  end

  get "logout" => "sesion#logout", :as => "logout"
  get "login" => "sesion#login", :as => "login"
  get "profile" => "sesion#profile", :as => "profile"
  get "password" => "sesion#password", :as => "password"
  get "evaluacions/:id/informe" => "evaluacions#informe", :as => :informe
  get "evaluacions/:id/to_excel" => "evaluacions#to_excel", :as => :to_excel

  match ':controller(/:action(/:id))(.:format)'

  root :to => 'evaluacions#index'

end

app/models/evaluacion.rb
class Evaluacion < ActiveRecord::Base
  attr_accessible :fechavisita, :jardin_id
  belongs_to :jardin
  belongs_to :evaluadora, :class_name => 'Usuario'
  has_many :salas
end

app/controllers/evaluacions_controller.rb
#<Encoding:UTF-8>
class EvaluacionsController < ApplicationController
  require 'spreadsheet'
  Spreadsheet.client_encoding = 'UTF-8'
  require 'gchart'
  require 'rtf'
  include RTF

  # ['Investigador', 0b01], ['Evaluador', 0b10], ['Coordinadora', 0b11]
  before_filter { |c| auth_and_check_privileges([0b10, 0b11]) }

  def index
    @intro = case @usuario_actual.permisos.to_i()
      when 0b10 then 'Todas las evaluaciones realizadas por ti'
      when 0b11 then 'Todas las evaluaciones'
    end

    @evaluaciones = case @usuario_actual.permisos.to_i()
      when 0b10
        then @usuario_actual.evaluacions
      when 0b11
        then Evaluacion.all
    end

  end

  def show
    @evaluacion = Evaluacion.find(params[:id])
  end


  def to_excel
    @evaluacion = Evaluacion.find(params[:id])

    book = Spreadsheet::Workbook.new
    header = Spreadsheet::Format.new :weight => :bold,
                                     :pattern_fg_color => :yellow,
                                     :pattern => 1

    @evaluacion.salas.each do |sala|
      sheet1 = book.create_worksheet :name => "#{sala.nombre}"

      sheet1.row(0).push "Jardin evaluado"
      sheet1.row(0).push @evaluacion.jardin.nombre
      sheet1.row(1).push "Fecha de la visita"
      sheet1.row(1).push @evaluacion.fechavisita.to_s
      sheet1.row(2).push "Evaluadora"
      sheet1.row(2).push @evaluacion.evaluadora.nombre
      sheet1.row(3).push "Sala"
      sheet1.row(3).push sala.nombre
      sheet1.row(4).push "Escala utilizada"

      if sala.escala_id == 1
        escalaName = "ITERS-R"
        escala = Escala.find_by_nombre("ITERS-R")
      elsif
      escalaName = "ECERS-R"
        escala = Escala.find_by_nombre("ECERS-R")
      end

      sheet1.row(4).push escalaName
      sheet1.row(6).concat %w{Nivel Calificacion Comentarios}
      sheet1.row(6).default_format = header
      i = 7
      escala.subescalas.each do |sub|
        sheet1.row(i).push sub.nombre
        sheet1.row(i).default_format = header
        i=i+1
        sub.items.each do |it|
          sheet1.row(i).push it.nombre

          i=i+1
        end
      end
      #respuestas = Indicador.indicadores_con_respuestas(sala.respuestas)
      #puntaje_itemes = Item.puntaje_itemes(respuestas)
      #sheet1.row(0).push puntaje_itemes.first.find(2).to_s
      #sheet1.row(1).push Item.puntaje_itemes(sala.respuestas).to_s
      #sheet1.row(0).push sala.puntajes_subescalas.to_s
    end

    spreadsheet = StringIO.new
    book.write spreadsheet
    send_data spreadsheet.string, :filename => "evaluacion.xls", :type =>  "application/vnd.ms-excel"

  end


  def informe
    @evaluacion = Evaluacion.find(params[:id])

    # Create required styles.
    styles = {}
    # Header for first page
    styles['CS_HEADER']               = CharacterStyle.new
    styles['CS_HEADER'].bold          = true
    styles['CS_HEADER'].font_size     = 36
    styles['PS_HEADER']               = ParagraphStyle.new
    styles['PS_HEADER'].justification = ParagraphStyle::CENTRE_JUSTIFY
    # H1
    styles['CS_H1']               = CharacterStyle.new
    styles['CS_H1'].bold          = true
    styles['CS_H1'].capitalize    = true
    styles['PS_H1']               = ParagraphStyle.new
    styles['PS_H1'].space_after   = 600 # doesn't work
    styles['PS_H1'].space_before  = 900
    # Normal
    styles['PS_NORMAL']               = ParagraphStyle.new
    styles['PS_NORMAL'].justification = ParagraphStyle::FULL_JUSTIFY
    styles['PS_NORMAL'].space_after   = 150
    styles['PS_NORMAL'].space_before  = 150
    # Footer
    styles['CS_FOOTER']           = CharacterStyle.new
    styles['CS_FOOTER'].font_size = 20

    document = Document.new(Font.new(Font::ROMAN, 'Arial'))

    # Portada
    document.paragraph(styles['PS_HEADER']) do |p|
      p.apply(styles['CS_HEADER']) do |s|
        10.times{ s.line_break }
        s << "INFORME DE RESULTADOS"
        2.times{ s.line_break }
        s << "Escalas de Calificación del ambiente Educativo"
        s.line_break
        s << "(ITERS-R/ECERS-R)"
        2.times{ s.line_break }
        s << @evaluacion.jardin.nombre
        10.times{ s.line_break }
        s << "EducaUC Inicial"
        s.line_break
        mes = case @evaluacion.fechavisita.month
        when 1  ; "Enero"
        when 2  ; "Febrero"
        when 3  ; "Marzo"
        when 4  ; "Abril"
        when 5  ; "Mayo"
        when 6  ; "Junio"
        when 7  ; "Julio"
        when 8  ; "Agosto"
        when 9  ; "Septiembre"
        when 10 ; "Octubre"
        when 11 ; "Noviembre"
        when 12 ; "Diciembre"
        end
        s << "#{mes} #{@evaluacion.fechavisita.year}"
      end
    end
    document.page_break

    # Presentación
    document.paragraph(styles['PS_NORMAL']) << ""
    document.paragraph(styles['PS_H1']).apply(styles['CS_H1']) do |q|
      q << "Presentación"
    end
    document.paragraph(styles['PS_NORMAL']) do |p|
      p.italic << "EducaUC Inicial "
      p << "como parte de su gestión, ha adoptado el uso de las Escalas de Calificación del Ambiente de la Infancia Temprana ITERS-R y ECERS-R, para establecer la calidad de los ambientes educativos de centros educativos de primera infancia. "
      p << "Estas Escalas fueron desarrolladas por investigadores del Centro de Desarrollo Infantil Frank Porter Graham, de la Universidad de Carolina del Norte de Estados Unidos y han sido parte importante de las investigaciones de primera infancia tanto en el extranjero como en nuestro país."
    end
    document.paragraph(styles['PS_NORMAL']) do |p|
      p << "El presente informe tiene como objetivo conocer y analizar los resultados obtenidos en la aplicación de ambos instrumentos evaluativos en el "
      p.bold << @evaluacion.jardin.nombre
      p << " de la comuna de #{@evaluacion.jardin.direccion.split(", ").last}. "
    end
    document.paragraph(styles['PS_NORMAL']) do |p|
      p << "Su estructura consta de tres apartados; en  el primero de ellos se da a conocer una breve descripción de las características de los instrumentos aplicados, acompañada del resumen de los contenidos que aborda cada Escala."
    end
    document.paragraph(styles['PS_NORMAL']) do |p|
      p << "Posteriormente, en el segundo punto, se entregan algunas consideraciones respecto a los procedimientos de aplicación y los resguardos que se  deben  considerar frente a los resultados de las Escalas de Calificación en términos generales."
    end
    document.paragraph(styles['PS_NORMAL']) do |p|
      p << "En tercer lugar, se presentan los resultados obtenidos por el " + @evaluacion.jardin.nombre + "; un breve resumen  de los resultados generales del Centro educativo y el detalle de cada sala evaluada."
    end
    document.page_break

    # I. Antecendentes de la escala
    document.paragraph(styles['PS_NORMAL']) << ""
    document.paragraph(styles['PS_H1']).apply(styles['CS_H1']) do |q|
      q << "I. Antecendentes de la escala"
    end
    document.paragraph(styles['PS_NORMAL']) do |p|
      p << "A continuación se detalla información respecto a las características principales de las Escalas aplicadas"
    end
    table = document.table(2, 3, 2400, 2800, 2800)
    table.cell_margin = 400
    table.border_width = 1
    table[0][0].bold << "Escalas"
    table[0][1].bold << "ITERS-R"
    table[0][2].bold << "ECERS-R"
    table[1][0].bold << "Rango de edad "
    table[1][1]      << "Desde los primeros meses hasta los 2 años y medio"
    table[1][2]      << "Desde los 2 años y medio hasta los 5 años"
    table = document.table(2, 2, 2400, 5600)
    table.cell_margin = 400
    table.border_width = 1
    table[0][0].bold << "Sub Escalas"
    table[0][1] << "• Espacio y Muebles"
    table[0][1].line_break
    table[0][1] << "• Rutinas de Cuidado Personal"
    table[0][1].line_break
    table[0][1] << "• Escuchar y Hablar / Lenguaje-Razonamiento"
    table[0][1].line_break
    table[0][1] << "• Actividades"
    table[0][1].line_break
    table[0][1] << "• Interacción"
    table[0][1].line_break
    table[0][1] << "• Estructura del programa"
    table[0][1].line_break
    table[0][1] << "• Padres y Personal"
    table[1][0].bold << "Antecendentes"
    table[1][1] << "Evalúan la calidad del proceso y cuantifican la observación de lo que ocurre en una sala de clases."
    2.times { table[1][1].line_break }
    table[1][1] << "Cuentan con respaldo científico: estudios de validación, confiabilidad y coherencia interna."
    2.times { table[1][1].line_break }
    table[1][1] << "Las fuentes principales para su creación tienen su base en evidencias empíricas: pruebas de investigación en el campo de la salud, del desarrollo y de la educación."
    2.times { table[1][1].line_break }
    table[1][1] << "Han sido utilizadas en importantes proyectos de investigación, lo que ha evidenciado su confiabilidad en a cuanto uso y validez (EEUU, Canadá, Alemania, Italia, Rusia, Inglaterra, Brasil, Hong Kong, Corea, entre otros)."
    document.page_break

    # Resumen de las Sub-escalas y los ítems para tipo de Escala (ITERS-R/ECERS-R)
    document.paragraph(styles['PS_NORMAL']) << ""
    document.paragraph(styles['PS_H1']).apply(styles['CS_H1']) do |q|
      q << "Resumen de las Sub-escalas y los ítems para tipo de Escala (ITERS-R/ECERS-R)"
    end
    escalas = ["ITERS-R", "ECERS-R"]
    table = document.table(2, 2, 4000, 4000)
    table.cell_margin = 400
    table.border_width = 1
    table[0][0].bold << escalas[0]
    table[0][1].bold << escalas[1]
    
    for c in 0..1
      count = 1
      Subescala.where(escala_id: Escala.where(nombre: escalas[c])).each do |s|
        table[1][c].bold << s.nombre
        table[1][c].line_break
        Item.where(subescala_id: s).each do |i|
          table[1][c] << "#{count}. #{i.nombre}"
          table[1][c].line_break
          count += 1
        end
      end
    end
    document.page_break

    # II. CONSIDERACIONES ACERCA DE LA APLICACIÓN Y RESULTADO DE LAS ESCALAS

app/helpers/evaluacion_helper.rb
module EvaluacionHelper
end

app/views/evaluacions/_form.html.erb
<%= form_for(@evaluacion) do |f| %>
  <% if @evaluacion.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @evaluacion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>Fecha de la visita<br> <%= f.date_select(:fechavisita, :order => [:day, :month, :year]) %></p>
  <p>Jardín<br> <%= f.select :jardin_id, @jardines %> o registra un <%= link_to "nuevo jardín", :new_jardin %>.</p>

<% if @evaluacion.id %>
  <%= link_to 'Nueva sala', new_evaluacion_sala_path(@evaluacion.id), :class => 'btn btn-success up-right' %>
  <% if @evaluacion.salas.empty? %>
  <p>Aún no has agregado ninguna sala a esta evaluación. Ingresa una sala más su escala aplicada con el botón 'Nueva sala'.</p>
  <% else %>
  <table class="table table-striped">
    <thead>
      <th>Sala</th>
      <th>Escala</th>
      <th class="headerIcono"></th>
      <th class="headerIcono"></th>
    </thead>
    <tbody>
      <% @evaluacion.salas.each do |sala| %>
      <% next if !sala.id? %>
      <tr>
        <td><%= sala.nombre %></td>
        <td><%= sala.escala.nombre %></td>
        <td class="headerIcono">
        <%= link_to edit_evaluacion_sala_path(sala.evaluacion_id, sala.id) do %>
          <i class="icon-pencil"></i>
        <% end %>
        </td>
        <td class="headerIcono">
        <%= link_to sala, method: :delete, data: { confirm: '¿Estás seguro?' } do %>
          <i class="icon-trash"></i>
        <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <% end %>
<% end %>

  <button id="evaluacion_button" type="submit" class="btn btn-success">
    <i class="icon-check"></i>  Guardar
  </button>
<% end %>

app/views/evaluacions/edit.html.erb
<h1>Editando la evaluación</h1>

<%= render 'form' %>

app/views/evaluacions/index.html.erb
<h1>Evaluaciones</h1>

<%= link_to 'Nueva evaluación', new_evaluacion_path, :class => 'btn btn-success up-right' %>



<% if !@evaluaciones.blank? %>
<p><%= @intro %></p>
<table class="table table-striped">
  <thead>
    <th>Jardín</th>
    <th>Fecha de visita</th>
    <th class="headerIcono"></th>
    <th class="headerIcono"></th>
  </thead>
  <tbody>
<% @evaluaciones.each do |evaluacion| %>
  <tr>
    <td><%= evaluacion.jardin.nombre %></td>
    <td><%= evaluacion.fechavisita %></td>
    <td class="headerIcono">
      <%= link_to evaluacion_path(evaluacion) do %>
        <i class="icon-arrow-right"></i>
      <% end %>
    </td>
    <td class="headerIcono">
      <%= link_to edit_evaluacion_path(evaluacion) do %>
        <i class="icon-pencil"></i>
      <% end %>
    </td>
    <td class="headerIcono">
      <%= link_to evaluacion, method: :delete, data: { confirm: '¿Estás seguro?' } do %>
        <i class="icon-trash"></i>
      <% end %>
    </td>
  </tr>
<% end %>
  </tbody>
</table>
<% else %>
<p>Aún no se han ingresado evaluaciones. 
    Haz clic en el botón <strong>nueva evaluación</strong> para agregar tu primera evaluación.</p>
<% end %>

app/views/evaluacions/new.html.erb
<h1>Nueva evaluación</h1>

<%= render 'form' %>
<%= link_to 'Volver', evaluacions_path %>

app/views/evaluacions/show.html.erb
<h1>Evaluación Número <%= @evaluacion.id %></h1>

<div class="up-right">
  <%= link_to 'Editar', edit_evaluacion_path(@evaluacion), :class => 'btn btn-primary' %>
<% if @evaluacion.salas.empty? %>
  <%= link_to 'Generar informe', '#', :class => 'btn btn-warning', :disabled => true %>
<% else %>
  <%= link_to 'Generar informe', informe_url(@evaluacion), :class => 'btn btn-warning' %>
<% end %>
  <%= link_to 'Exportar a Excel', to_excel_url, :class => 'btn btn-warning' %>
  <a class="btn btn-inverse">Ver Estadisticas</a>
</div>

<table class="table table-striped">
	<tbody>
		<tr>
		<td><strong>Fecha de la visita:</strong></td><td><%= @evaluacion.fechavisita %></td>
		</tr>
		<tr>
		<td><strong>Salas evaluadas:</strong></td><td><%= @evaluacion.salas.length %></td>
		</tr>
		<tr>
		<td><strong>Jardín:</strong></td><td><%= @evaluacion.jardin.nombre %></td>
		</tr>
	</tbody>
</table>

<% if @evaluacion.salas.empty? %>
  <p>Esta evaluación aún no cuenta con ninguna sala ingresada.</p>
<% else %>
  <table class="table table-striped">
    <thead>
      <th>Sala</th>
      <th>Escala</th>
      <th class="headerIcono"></th>
      <th class="headerIcono"></th>
    </thead>
    <tbody>
      <% @evaluacion.salas.each do |sala| %>
      <tr>
        <td><%= sala.nombre %></td>
        <td><%= sala.escala.nombre %></td>
        <td class="headerIcono">
        <%= link_to evaluacion_sala_path(sala.evaluacion_id, sala.id) do %>
          <i class="icon-arrow-right"></i>
        <% end %>
        </td>
        <td class="headerIcono">
        <%= link_to sala, method: :delete, data: { confirm: '¿Estás seguro?' } do %>
          <i class="icon-trash"></i>
        <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% end %>