config/routes.rb
Educaucinicial::Application.routes.draw do

  get "escalas/new"

  get "escalas/create"

  get "escalas/index"

  get "escalas/show"

  get "escalas/edit"

  get "escalas/update"

  get "escalas/destroy"

  resources :usuarios, :jardins, :escalas, :salas

  resources :evaluacions do
    resources :salas
  end

  get "logout" => "sesion#logout", :as => "logout"
  get "login" => "sesion#login", :as => "login"
  get "profile" => "sesion#profile", :as => "profile"
  get "password" => "sesion#password", :as => "password"
  get "evaluacions/:id/informe" => "evaluacions#informe", :as => :informe
  get "evaluacions/:id/to_excel" => "evaluacions#to_excel", :as => :to_excel

  match ':controller(/:action(/:id))(.:format)'

  root :to => 'evaluacions#index'

end

app/models/usuario.rb
require 'valid_email/email_validator'
class Usuario < ActiveRecord::Base
  attr_accessible :email, :nombre, :password, :password_confirmation, :permisos
  has_many :evaluacions, :class_name => 'Evaluacion', :foreign_key => 'evaluadora_id'

  attr_accessor :password
  validates :nombre, :presence => true
  validates :email, :presence => true, :uniqueness => true, :email => true
  validates :password, :confirmation => true #password_e_confirmation attr
  validates_length_of :password, :in => 6..25, :on => :create

  before_save :encrypt_password
  after_save :clear_password

  def encrypt_password
    if password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.password_e = BCrypt::Engine.hash_secret(password, salt)
    end
  end

  def clear_password
    self.password = nil
  end

  def self.authenticate(email="", login_password="")
    user = Usuario.find_by_email(email)

    if user && user.match_password(login_password)
      return user
    else
      return false
    end
  end   

  def match_password(login_password="")
    password_e == BCrypt::Engine.hash_secret(login_password, salt)
  end
end

app/controllers/usuarios_controller.rb
#<Encoding:UTF-8>
class UsuariosController < ApplicationController
  
  # Sólo pueden acceder los coordinadores
  before_filter { |c| auth_and_check_privileges([0b11]) }

  def new
    @usuario = Usuario.new
  end

  def create
    @usuario = Usuario.new(params[:usuario])
    if @usuario.save
      redirect_to :action => :index
    else
      flash[:notice] = "Form is invalid"
      render "new"
    end
  end

  def index
    @usuarios = Usuario.all
  end

  def show
    @usuario = Usuario.find(params[:id])
  end

  def edit
    @usuario = Usuario.find(params[:id])
  end

  def update
    @usuario = Usuario.find(params[:id])
    if params[:current_password]
      usuario_autorizado = Usuario.authenticate(@usuario_actual.email,params[:current_password])
      if usuario_autorizado
        if @usuario.update_attributes(params[:usuario])
          redirect_to @usuario
        else
          flash[:notice] = "Password Confirmation no coincide con la Nueva Password"
          redirect_to :controller => "sesion", :action => "password"
        end
      else
        flash[:notice] = "Password Actual Invalida"
        redirect_to :controller => "sesion", :action => "password"
      end
    elsif @usuario.update_attributes(params[:usuario])
      redirect_to @usuario
    else
      render action: "edit"
    end
  end

  def destroy
    Usuario.find(params[:id]).destroy
    redirect_to :action => :index
  end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
    <% if @usuario.errors.any? %>
        <div id="error_explanation">
          <ul>
            <% @usuario.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>Nombre:<br> <%= f.text_field :nombre%> </p>

    <p>Email:<br> <%= f.text_field :email%> </p>

    <% if !@usuario.id? %>
        <p>Password:<br> <%= f.password_field :password%></p>

        <p>Password Confirmation:<br> <%= f.password_field :password_confirmation%> </p>
    <% end %>

    <p>Rol:<br> <%= f.select :permisos, [['Investigador', 0b01], ['Evaluador', 0b10], ['Coordinadora', 0b11]] %></p>

    <button type="submit" class="btn btn-success">
      <i class="icon-check"></i>  Guardar
    </button>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editando el Usuario</h1>
<%= render 'form' %>

app/views/usuarios/index.html.erb
<h1>Usuarios</h1>

<%= link_to 'Nuevo usuario', new_usuario_path, :class => 'btn btn-success up-right' %>

<% if !@usuarios.blank? %>
    <table class="table table-striped">
      <thead>
        <th>Nombre del usuario</th>
        <th>Email</th>
        <th>Cargo</th>
        <th class="headerIcono"></th>
        <th class="headerIcono"></th>
      </thead>

      <% @usuarios.each do |usuario| %>
          <tr>
            <td><%= link_to usuario.nombre, usuario %></td>
            <td><%= usuario.email %></td>
            <% if usuario.permisos.to_i == 1 %>
                <td> Investigador </td>
            <% elsif usuario.permisos.to_i == 2 %>
                <td> Evaluadora </td>
            <% else %>
                <td> Coordinadora </td>
            <% end %>
            <td class="headerIcono">
              <%= link_to edit_usuario_path(usuario) do %>
                  <i class="icon-pencil"></i>
              <% end %>
            </td>
            <td class="headerIcono">
              <%= link_to usuario, method: :delete, data: { confirm: '¿Estás seguro?' } do %>
                  <i class="icon-trash"></i>
              <% end %>
            </td>
          </tr>
      <% end %>
    </table>
<% else %>
    <p>Error al cargar usuarios</p>
<% end -%>

app/views/usuarios/new.html.erb
<h1>Nuevo usuario</h1>

<%= render 'form' %>
<%= link_to 'Volver', usuarios_path %>

app/views/usuarios/show.html.erb
<h1>Usuario</h1>
<h2><%= @usuario.nombre %></h2>

<p>Email:<br> <%= @usuario.email %></p>

<p>Cargo:<br>
  <% if @usuario.permisos.to_i == 1 %>
      <%= 'Investigador' %></p>
  <% elsif @usuario.permisos.to_i == 2 %>
      <%= 'Evaluadora' %></p>
  <% else %>
          <%= 'Coordinadora' %></p>
  <% end %>

  <% if @usuario_actual.permisos.to_i == 3 %>
      <%= link_to 'Editar', edit_usuario_path(@usuario) %>
      <%= link_to 'Volver', usuarios_path %>
  <% end %>