config/routes.rb
Educaucinicial::Application.routes.draw do

  get "escalas/new"

  get "escalas/create"

  get "escalas/index"

  get "escalas/show"

  get "escalas/edit"

  get "escalas/update"

  get "escalas/destroy"

  resources :usuarios, :jardins, :escalas, :salas

  resources :evaluacions do
    resources :salas
  end

  get "logout" => "sesion#logout", :as => "logout"
  get "login" => "sesion#login", :as => "login"
  get "profile" => "sesion#profile", :as => "profile"
  get "password" => "sesion#password", :as => "password"
  get "evaluacions/:id/informe" => "evaluacions#informe", :as => :informe
  get "evaluacions/:id/to_excel" => "evaluacions#to_excel", :as => :to_excel

  match ':controller(/:action(/:id))(.:format)'

  root :to => 'evaluacions#index'

end

app/models/sala.rb
class Sala < ActiveRecord::Base
  attr_accessible :nombre, :respuestas, :comentarios, :evaluadora_id, :escala_id, :evaluacion_id
  belongs_to :evaluacion
  belongs_to :escala

  def puntajes_subescalas
  	respuestas = Indicador.indicadores_con_respuestas(self.respuestas)
    puntaje_itemes = Item.puntaje_itemes(respuestas)
    puntaje_subescalas = Subescala.puntaje_subescalas(puntaje_itemes)
    puntaje_subescalas
  end
end

app/controllers/salas_controller.rb
#<Encoding:UTF-8>
class SalasController < ApplicationController

  # ['Investigador', 0b01], ['Evaluador', 0b10], ['Coordinadora', 0b11]
  before_filter { |c| auth_and_check_privileges([0b10, 0b11]) }

  def index
    @salas = Sala.where(:evaluacion_id => params[:evaluacion_id])
  end

  def show
    @sala = Sala.find(params[:id])
  end

  def new
    @sala = Evaluacion.find(params[:evaluacion_id]).salas.build
    list_of_escalas
  end

  def edit
    @sala = Sala.find(params[:id])
    list_of_escalas
  end

  def create
    @sala = Sala.new(params[:sala])

    if @sala.save
      redirect_to edit_evaluacion_sala_path(@sala.evaluacion_id, @sala.id), notice: 'La nueva sala fue creada.'
    else
      render action: "new"
    end
  end

  def update
    @sala = Sala.find(params[:id])

    if @sala.update_attributes(params[:sala])
      redirect_to evaluacion_sala_path(@sala.id), notice: 'Los cambios se guardaron exitosamente.'
    else
      render action: "edit"
    end
  end

  def destroy
    @sala = Sala.find(params[:id])
    @sala.destroy
    redirect_to edit_evaluacion_path(@sala.evaluacion_id)
  end

  protected
    def list_of_escalas
      @escalas = [['Selecciona una escala', -1]]
      Escala.all.each do |e|
        @escalas.append [e.nombre, e.id]
      end
    end
end

app/helpers/salas_helper.rb
module SalasHelper
end

app/views/salas/_form.html.erb
<%= form_for(@sala) do |f| %>
  <% if @sala.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @sala.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <p>Nombre de la sala<br> <%= f.text_field :nombre %></p>
  <% if !@sala.id? %>
    <%= f.hidden_field :evaluacion_id, :value => params[:evaluacion_id] %>
    <p>Escala aplicada<br> <%= f.select :escala_id, @escalas %></p>
  <% else %>
    <h5> Respuestas </h5>
    <div class="accordion" id="accordion1">
      <% @sala.escala.subescalas.each do |subescala| %>
        <div class="accordion-group">
          <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="accordion1" href="#subescala<%= subescala.id %>">
              <%= subescala.nombre %>
            </a>
          </div>
          <div id="subescala<%= subescala.id %>" class="accordion-body collapse">
            <div class="accordion-inner">
              <% subescala.items.each  do |item| %>
                <div class="accordion-group">
                  <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#subescala<%= subescala.id %>accordion2" href="#item<%= item.id %>">
                      <%= item.nombre %>
                    </a>
                  </div>
                  <div id="item<%= item.id %>" class="accordion-body collapse">
                    <div class="accordion-inner">
                      <table class="table table-striped table-bordered table-condensed">
                        <thead>
                          <th></th>
                          <th>S</th>
                          <th>N</th>
                          <th>NA</th>
                          <th>Info</th>
                        </thead>
                        <tbody>
                          <% item.indicadors.each  do |indicador| %>
                          <tr>
                            <td><%= indicador.numero %></td>
                            <td><input type="radio" name="<%= item.id.to_s() + '-' + indicador.numero.to_s() %>" value="s"></td>
                            <td><input type="radio" name="<%= item.id.to_s() + '-' + indicador.numero.to_s() %>" value="n"></td>
                            <td>
                            <% if !indicador.absoluto %>
                              <input type="radio" name="<%= item.id.to_s() + '-' + indicador.numero.to_s() %>" value="na">
                            <% end %>
                            </td>
                            <td><%= indicador.texto %></td>
                          </tr>
                          <% end %>
                        </tbody>
                      </table>
                      <p>Comentarios<br> <%= text_area_tag("comentario_#{item.id}") %></p>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
  <%= f.hidden_field :respuestas %>
  <%= f.hidden_field :comentarios %>
  <button type="submit" class="btn btn-success">
    <i class="icon-check"></i>  Guardar
  </button>

<% end %>

app/views/salas/edit.html.erb
<h1>Editando <%= @sala.nombre %></h1>

<%= render 'form' %>

app/views/salas/index.html.erb
<h1>Listing salas</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Evaluacion</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @salas.each do |sala| %>
  <tr>
    <td><%= sala.nombre %></td>
    <td><%= sala.evaluacion %></td>
    <td><%= link_to 'Show', sala %></td>
    <td><%= link_to 'Edit', edit_sala_path(sala) %></td>
    <td><%= link_to 'Destroy', sala, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sala', new_sala_path %>

app/views/salas/new.html.erb
<h1>Nueva sala</h1>

<%= render 'form' %>

<%= link_to 'Atrás', edit_evaluacion_path(@sala.evaluacion) %>

app/views/salas/show.html.erb
<h1><%= @sala.nombre %></h1>

<div class="up-right">
  <%= link_to @sala.evaluacion, :class => 'btn btn-success' do %>
    <i class="icon-white icon-arrow-left"></i>Vuelve a la evaluación
  <% end %>
  <%= link_to 'Editar la sala', edit_sala_path(@sala), :class => 'btn btn-primary' %>
</div>

<table class="table table-striped">
  <tbody>
    <tr>
    <td><strong>Jardín:</strong></td>
    <td><%= @sala.evaluacion.jardin.nombre %></td>
    </tr>
    <tr>
    <td><strong>Escala utilizada:</strong></td>
    <td><%= @sala.escala.nombre %></td>
    </tr>
  </tbody>
</table>

<p class="hidden" id="showRespuestas"><%= @sala.respuestas %></p>
<p class="hidden" id="showComentarios"><%= @sala.comentarios %></p>

<h5> Respuestas </h5>
<div class="accordion" id="accordion1">
  <% @sala.escala.subescalas.each do |subescala| %>
    <div class="accordion-group">
      <div class="accordion-heading">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="accordion1" href="#<%= subescala.nombre.delete(' ') %><%= subescala.id %>">
          <%= subescala.nombre %>
        </a>
      </div>
      <div id="<%= subescala.nombre.delete(' ') %><%= subescala.id %>" class="accordion-body collapse">
        <div class="accordion-inner">
          <% subescala.items.each  do |item| %>
            <div class="accordion-group">
              <div class="accordion-heading">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#<%= subescala.nombre.delete(' ') %><%= subescala.id %>accordion2" href="#<%= item.nombre.delete(' ') %><%= item.id %>">
                  <%= item.nombre %>
                </a>
              </div>
              <div id="<%= item.nombre.delete(' ') %><%= item.id %>" class="accordion-body collapse">
                <div class="accordion-inner">
                  <table class="table table-striped table-bordered table-condensed">
                    <thead>
                      <th></th>
                      <th>S</th>
                      <th>N</th>
                      <th>NA</th>
                      <th>Info</th>
                    </thead>
                    <tbody>
                      <% item.indicadors.each do |indicador| %>
                      <tr>
                        <td><%= indicador.numero %></td>
                        <td><i class="" name="<%= item.id.to_s() + '-' + indicador.numero.to_s() %>" value="s"></i></td>
                        <td><i class="" name="<%= item.id.to_s() + '-' + indicador.numero.to_s() %>" value="s"></i></td>
                        <td><i class="" name="<%= item.id.to_s() + '-' + indicador.numero.to_s() %>" value="s"></i></td>
                        <td><%= indicador.texto %></td>
                      </tr>
                      <% end %>
                    </tbody>
                  </table>
                  <p><b>Comentarios:</b></p>
                  <p id=<%= "comentario_#{item.id}" %> ></p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>